package com.civicdesk.module.citizen.entity;

import com.civicdesk.module.citizen.entity.converter.CitizenStatusConverter;
import com.civicdesk.module.citizen.entity.enums.CitizenStatus;
import com.civicdesk.module.citizen.entity.enums.Gender;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import org.hibernate.annotations.Check;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * A registered citizen. Maps to the {@code citizen_profile} table (snake_case).
 *
 * <p>{@code citizen_id} is a 16-character alphanumeric id generated by the service layer
 * ({@code IdGenerator}). {@code gender} persists as its String name; {@code status} persists as a
 * single-character code (A/V/F) via {@link CitizenStatusConverter}. Both are also guarded by a DB
 * CHECK constraint so an invalid value is rejected at the database too.
 */
@Entity
@Table(
        name = "citizen_profile",
        // Backs CitizenProfileRepository.findByWard (GET /getCitizensByWard/{ward}).
        indexes = @Index(name = "idx_citizen_profile_ward", columnList = "ward")
)
public class CitizenProfile {

    @Id
    @Column(name = "citizen_id", length = 16, nullable = false, updatable = false)
    private String citizenId;

    @Column(name = "name", nullable = false)
    private String name;

    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    @Enumerated(EnumType.STRING)
    @Column(name = "gender", length = 10)
    @Check(constraints = "gender in ('Male','Female','Other')")
    private Gender gender;

    @Column(name = "national_id_number", unique = true, length = 50)
    private String nationalIdNumber;

    @Column(name = "address")
    private String address;

    @Column(name = "ward", nullable = false)
    private String ward;

    @Column(name = "zone")
    private String zone;

    @Column(name = "email", nullable = false, unique = true)
    private String email;

    @Column(name = "phone", nullable = false, length = 20)
    private String phone;

    @Convert(converter = CitizenStatusConverter.class)
    @Column(name = "status", nullable = false, length = 1)
    @Check(constraints = "status in ('A','V','F')")
    private CitizenStatus status;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    public String getCitizenId() {
        return citizenId;
    }

    public void setCitizenId(String citizenId) {
        this.citizenId = citizenId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public String getNationalIdNumber() {
        return nationalIdNumber;
    }

    public void setNationalIdNumber(String nationalIdNumber) {
        this.nationalIdNumber = nationalIdNumber;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getWard() {
        return ward;
    }

    public void setWard(String ward) {
        this.ward = ward;
    }

    public String getZone() {
        return zone;
    }

    public void setZone(String zone) {
        this.zone = zone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public CitizenStatus getStatus() {
        return status;
    }

    public void setStatus(CitizenStatus status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }
}
