package com.civicdesk.module.serviceRequest.repository;

import com.civicdesk.module.iam.entity.User;
import com.civicdesk.module.iam.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Slice test for {@link UserRepository#findByRoleAndStatusAndDepartmentId}, used by the
 * Service Request module's officer auto-assignment to find active field officers (role
 * {@code FO}, status {@code A}) in a department. User ids are generated by IAM, so the
 * seeded officers' ids are captured after flush rather than assigned.
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class UserRepositoryTest {

    @Autowired private TestEntityManager em;
    @Autowired private UserRepository repository;

    private String activeOfficerA1;
    private String activeOfficerA2;

    @BeforeEach
    void seed() {
        User a = officer("Active Officer A", "a@city.gov", "DEP-A", "A");
        User b = officer("Active Officer A2", "b@city.gov", "DEP-A", "A");
        User c = officer("Inactive Officer A", "c@city.gov", "DEP-A", "I");
        User d = officer("Active Officer B", "d@city.gov", "DEP-B", "A");
        User citizen = user("Citizen", "e@city.gov", "CIT", null, "A");

        em.persist(a);
        em.persist(b);
        em.persist(c);
        em.persist(d);
        em.persist(citizen);
        em.flush();

        activeOfficerA1 = a.getUserId();
        activeOfficerA2 = b.getUserId();
        em.clear();
    }

    @Test
    @DisplayName("returns only active officers in the requested department")
    void findsActiveOfficersInDepartment() {
        assertThat(repository.findByRoleAndStatusAndDepartmentId("FO", "A", "DEP-A"))
                .extracting(User::getUserId)
                .containsExactlyInAnyOrder(activeOfficerA1, activeOfficerA2);
    }

    @Test
    @DisplayName("returns empty when no active officer matches")
    void emptyWhenNoMatch() {
        assertThat(repository.findByRoleAndStatusAndDepartmentId("FO", "A", "DEP-Z")).isEmpty();
        assertThat(repository.findByRoleAndStatusAndDepartmentId("FO", "I", "DEP-B")).isEmpty();
    }

    private User officer(String name, String email, String departmentId, String status) {
        return user(name, email, "FO", departmentId, status);
    }

    private User user(String name, String email, String role, String departmentId, String status) {
        User u = new User();
        u.setName(name);
        u.setEmail(email);
        u.setRole(role);
        u.setDepartmentId(departmentId);
        u.setStatus(status);
        return u;
    }
}
